version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.2.4
    - 8.0.0
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.4
    - 8.0.5
    - 8.1.0
